name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Set up Chrome
        run: |
          sudo apt-get update sudo apt-get install -y google-chrome-stable google-chrome --version 

      - name: Set up ChromeDriver
        run: |
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip unzip chromedriver_linux64.zip -d /usr/local/bin/ chmod +x /usr/local/bin/chromedriver chromedriver --version

      - name: Run Maven build
        run: mvn clean verify -DskipTests=false -e -X

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
         name: test-reports
         path: target/surefire-reports/
